services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    networks:
      - laravel
    depends_on:
      - postgres

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - laravel

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    networks:
      - laravel
    depends_on:
      - app

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
